### ISSUE TITLE
Authenication fails for multi-projects and when task are ran before publishing.

### ISSUE THREAD

**Issue by egast** [gilcloud/sbt-gitlab#7] opened 2020-08-26 12:07 UTC
I'm using version 0.0.4 and publishing to GitLab only works for SBT with a single project configuration. When I try to publish artifacts from a multi-project SBT configuration, then an `access to url ".." was refused by the server: Unauthorized` exception is thrown.
I have the same behavior when running a task before publishing, for example `sbt test publish`

**Comment by listba** [comment] 2020-08-28 15:59
This was driving me crazy last night as well. I got past it by setting up a multi-staged pipeline, but itss definitely less than ideal and took forever to track down the root cause.

eg: ci
```.gitlab-ci.yml
stages:
  - test
  - publish

test_build:
  stage: test
  script:
    - sbt clean test

publish_build:
  stage: publish
  script:
    - sbt clean publish
`

**Comment by gilandose** [comment] 2020-08-28 20:34
will try to get a look at this soon, if you find the root cause I'm happy to take a PR for it.

**Comment by listba** [comment] 2020-08-29 03:52
I poked at it a bit, but I don't have ~~much~~ any experience with sbt plugins so this is foreign territory for me.

With the debug log level on one oddity I noticed is with that it seems to be attempting to send the request twice and the error gets thrown after the second. no pom ever shows up in gitlab as far as I can tell. 

Is there a way to capture the full request/response in the plugin?

```log
[debug] injecting gitlab token for Request{method=PUT, url=https://gitlab.com/api/v4/projects/20785586/packages/maven/net/benlist/scala-publish-test_2.13/0.1.3-SNAPSHOT/scala-publish-test_2.13-0.1.3-SNAPSHOT.pom, tags={}}
[debug] Request{method=PUT, url=https://gitlab.com/api/v4/projects/20785586/packages/maven/net/benlist/scala-publish-test_2.13/0.1.3-SNAPSHOT/scala-publish-test_2.13-0.1.3-SNAPSHOT.pom, tags={}}
[debug] Content-Type: application/octet-stream
[debug] Content-Length: 1030
[debug] Host: gitlab.com
[debug] Connection: Keep-Alive
[debug] Accept-Encoding: gzip
[debug] User-Agent: okhttp/3.14.2
[debug] Private-Token:  [redacted]
[debug] injecting gitlab token for Request{method=PUT, url=https://gitlab.com/api/v4/projects/20785586/packages/maven/net/benlist/scala-publish-test_2.13/0.1.3-SNAPSHOT/scala-publish-test_2.13-0.1.3-SNAPSHOT.pom, tags={}}
[debug] Request{method=PUT, url=https://gitlab.com/api/v4/projects/20785586/packages/maven/net/benlist/scala-publish-test_2.13/0.1.3-SNAPSHOT/scala-publish-test_2.13-0.1.3-SNAPSHOT.pom, tags={}}
[debug] Content-Type: application/octet-stream
[debug] Content-Length: 1030
[debug] Host: gitlab.com
[debug] Connection: Keep-Alive
[debug] Accept-Encoding: gzip
[debug] User-Agent: okhttp/3.14.2
[debug] Private-Token: [redacted]
[debug] Private-Token: [redacted]
```

**Comment by gilandose** [comment] 2020-09-07 14:42
closing as this should be resolve by above PR

**Closed by gilandose** 2020-09-07 14:42 UTC
